server:
  port: 8002

spring:
  application:
    name: cloud-provider



#把客户端注册到服务列表中
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  #设置入驻的服务的名称，是唯一的
  instance:
    instance-id: cloud-provider8002
    #访问路径显示ip
    prefer-ip-address: true