server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true
      routes:
        - id: provider_routh      #路由的ID，没有固定规则但要求唯一，简易配合服务名
#          uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://cloud-provider   #匹配后提供服务的路由地址
          predicates:
            - Path=/user/get/**          #断言，路径相匹配的进行路由

        - id: provider_routh   #路由的ID，没有固定规则但要求唯一，简易配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-provider     #匹配后提供服务的路由地址
          predicates:
            - Path=/user/get2/**             #断言，路径相匹配的进行路由
            - After=2020-04-09T21:15:28.872+08:00[Asia/Shanghai]
            - Method=GET

eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: cloud-gateway
    #访问路径显示ip
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
